theme: jekyll-theme-minimal
title: SlickStack
description: SlickStack is a free LEMP stack automation script written in Bash designed to enhance and simplify WordPress provisioning, performance, and security.
