name: Mirror to SourceForge

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Perform a full clone instead of a shallow clone

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCEFORGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan git.code.sf.net >> ~/.ssh/known_hosts

      - name: Debug Git Remote
        run: |
          echo "Checking Git remote..."
          git remote add sourceforge ssh://jessuppi@git.code.sf.net/p/slickstack/code
          git remote -v

      - name: Push to SourceForge
        run: |
          echo "Pushing code to SourceForge..."
          git push sourceforge master --force
